version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    ports:
      - ${DATALAB_ELK_ELASTICSEARCH_PORT1}:9200
      - ${DATALAB_ELK_ELASTICSEARCH_PORT2}:9300
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - datalab-network
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:7.9.3
    ports:
      - ${DATALAB_ELK_LOGSTASH_PORT1}:5000
      - ${DATALAB_ELK_LOGSTASH_PORT2}:9600
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - datalab-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.3
    ports:
      - ${DATALAB_ELK_ELASTICSEARCH_KIBANA}:5601
    networks:
      - datalab-network
    environment:
      server.name: kibana
      server.host: "0"
      elasticsearch.hosts: http://elasticsearch:9200

networks:
  datalab-network:
    external: true

volumes:
  elasticsearch_data:
    external: true
