version: '3.7'

services:
  mysql:
    image: mysql:8.0.22
    ports:
      - ${DATALAB_MYSQL_PORT}:3306
    networks:
      - datalab-network
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    restart: unless-stopped

networks:
  datalab-network:
    external: true

volumes:
  mysql_data:
    external: true
