# See https://neo4j.com/docs/operations-manual/current/docker/operations/
version: "3.7"

services:
  neo4j:
    image: neo4j:4.1.3
    volumes:
      - "${DATALAB_DATA_DIR}/neo4j:/data"
      # You're mounting the Host path from the controlboard!
      # Not a path from within the controlboard container
      - "${DATALAB_SOURCECODE_DIR}/datalab/datalab-stacks/neo4j/plugins:/plugins"
    ports:
      - 7474:7474
      - 7687:7687
    networks:
      - datalab-network
    environment:
      # Disable authentication entirely. Set a password in production!
      - NEO4J_AUTH=none
      # Enable the plugins (files in the neo4j/plugins directory)
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
      - NEO4J_dbms_security_procedures_whitelist=apoc.*,gds.*
    restart: unless-stopped

networks:
  datalab-network:
    external: true
